notifications:
  email:
    on_success: never
language: csharp
sudo: required
dist: trusty
mono: 4.0.5
dotnet: 1.0.0-preview2-003131
script:
- dotnet restore -v Minimal
- dotnet build **/project.json -c Release
- cd tests/TinyPng.Tests
- dotnet test
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi

